In [263]:
import pandas as pd
import numpy as np
import random

In [264]:
path = "csv_files/detection_graph.csv"

In [265]:
df = pd.read_csv(path)

In [266]:
df

         name  number     x      y     z
0      conn_a     104  20.0  -50.0  -9.0
1   conn_f_30      30  12.0  -86.0   0.0
2   conn_f_37      37  17.0 -115.0  -9.0
3   conn_f_60      60 -24.0 -120.0 -16.0
4      conn_e      10  -5.0  -87.0 -12.0
5      conn_c      14  -3.0  -87.0 -12.0
6     bag_b_l      55 -20.0 -120.0 -10.0
7         box      53 -15.0  -70.0   0.0
8      conn_g      80 -25.0 -114.0  -9.0
9      conn_h      82 -21.0 -115.0   0.0
10     conn_k      45   0.0 -104.0 -10.0
11     conn_d      38  13.0 -129.0  -9.0
12    bag_b_r     224  16.0 -105.0  -5.0
13    bag_a_r     236  13.0 -150.0   0.0
14     conn_b     222  21.0  -86.0   0.0
15     conn_i     212  16.0  -75.0   3.0
16     conn_j     214  22.0  -73.0   3.0
17    bag_a_l      98 -25.0 -225.0   0.0

In [267]:
#for each element in 'name' column create a column with the name
for i in range(len(df)):
    df[df['name'][i]] = 0

In [268]:
names_list = df['name'].tolist()

In [269]:
tmp = [1,2,3,4]
print(f"len(tmp): {len(tmp)}")
for i,v in enumerate(tmp):
    print(i,v)

len(tmp): 4
0 1
1 2
2 3
3 4

In [270]:
# for row
for i in range(len(df)):
    name = df["name"][i]
    current_softmax = random.uniform(0.51, 0.9)
    df[name][i] = current_softmax
    random_names = random.sample(names_list, random.randint(1, len(names_list)))
    if name in random_names:
        random_names.remove(name)
    other_values = [random.randint(1,100) for i in range(len(random_names))]
    #normalize to 1
    other_values = [(float(i)/np.sum(other_values))*(1-current_softmax) for i in other_values]
    for j in range(len(random_names)):
        df[random_names[j]][i] = other_values[j]

/tmp/ipykernel_1734/2856577721.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[name][i] = current_softmax
/tmp/ipykernel_1734/2856577721.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[random_names[j]][i] = other_values[j]

In [271]:
df

,name,number,x,y,z,conn_a,conn_f_30,conn_f_37,conn_f_60,conn_e,...,conn_g,conn_h,conn_k,conn_d,bag_b_r,bag_a_r,conn_b,conn_i,conn_j,bag_a_l
0,conn_a,104,20.0,-50.0,-9.0,0.646812,0.035957,0.008699,0.038856,0.004640,...,0.011019,0.006379,0.005799,0.000000,0.027837,0.040016,0.002900,0.028417,0.050455,0.009279
1,conn_f_30,30,12.0,-86.0,0.0,0.008623,0.802574,0.000000,0.000000,0.039939,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.021331,0.029047,0.004085,0.019516
2,conn_f_37,37,17.0,-115.0,-9.0,0.000000,0.001351,0.638722,0.000000,0.018233,...,0.033764,0.015532,0.011480,0.029713,0.015532,0.000000,0.064828,0.040517,0.017557,0.018908
3,conn_f_60,60,-24.0,-120.0,-16.0,0.000000,0.000000,0.000000,0.602629,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.127726,0.000000,0.077041,0.192603,0.000000
4,conn_e,10,-5.0,-87.0,-12.0,0.029480,0.000000,0.000000,0.000000,0.777803,...,0.000000,0.040039,0.000000,0.000000,0.000000,0.016720,0.030800,0.000000,0.016280,0.005720
5,conn_c,14,-3.0,-87.0,-12.0,0.000000,0.017976,0.004299,0.000000,0.014459,...,0.000000,0.000000,0.000000,0.008597,0.010551,0.009769,0.000000,0.033216,0.026573,0.000000
6,bag_b_l,55,-20.0,-120.0,-10.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.083649,0.000000,0.000000,0.179248,0.000000,0.000000,0.000000
7,box,53,-15.0,-70.0,0.0,0.004749,0.000000,0.019314,0.010448,0.017097,...,0.025330,0.030395,0.025646,0.020264,0.000000,0.010448,0.007282,0.030395,0.000000,0.027862
8,conn_g,80,-25.0,-114.0,-9.0,0.000000,0.000000,0.054038,0.000000,0.000000,...,0.834115,0.000000,0.032674,0.000000,0.022621,0.000000,0.000000,0.056552,0.000000,0.000000
9,conn_h,82,-21.0,-115.0,0.0,0.051954,0.004422,0.037584,0.000000,0.052507,...,0.000000,0.797710,0.000000,0.000000,0.000000,0.000000,0.033162,0.003869,0.018792,0.000000
10,conn_k,45,0.0,-104.0,-10.0,0.049082,0.000000,0.042498,0.053871,0.058660,...,0.000000,0.003591,0.680366,0.000000,0.011971,0.000000,0.000000,0.011373,0.000000,0.019154
11,conn_d,38,13.0,-129.0,-9.0,0.012438,0.003015,0.022238,0.000000,0.022238,...,0.000000,0.000000,0.000000,0.814938,0.028268,0.000000,0.030530,0.006031,0.024499,0.001885
12,bag_b_r,224,16.0,-105.0,-5.0,0.002887,0.001083,0.024901,0.007218,0.006135,...,0.016962,0.027428,0.034284,0.005413,0.742687,0.020210,0.012270,0.011909,0.007218,0.018405
13,bag_a_r,236,13.0,-150.0,0.0,0.010259,0.012396,0.042745,0.003420,0.028212,...,0.003847,0.012824,0.035906,0.013251,0.032059,0.691379,0.025647,0.000427,0.013679,0.014961
14,conn_b,222,21.0,-86.0,0.0,0.000000,0.000000,0.099535,0.000000,0.068679,...,0.000000,0.000000,0.000000,0.000000,0.000995,0.048772,0.607830,0.049768,0.000000,0.088587
15,conn_i,212,16.0,-75.0,3.0,0.000000,0.019109,0.020557,0.015056,0.002895,...,0.010713,0.025479,0.028085,0.013318,0.012160,0.014187,0.019978,0.770112,0.025479,0.005791
16,conn_j,214,22.0,-73.0,3.0,0.010346,0.000000,0.019778,0.016127,0.010346,...,0.010346,0.010041,0.000000,0.020996,0.030124,0.020083,0.027385,0.000000,0.758095,0.020996
17,bag_a_l,98,-25.0,-225.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.055707,0.000000,0.000000,0.000000,0.819434

In [272]:
#check if sum of each row is 1
for i in range(len(df)):
    #sum colums value from names_lsit
    sum = 0
    for name in names_list:
        sum += df[name][i]
    print(f"sum: {sum} for row: {i}")

sum: 0.9999999999999999 for row: 0
sum: 1.0000000000000002 for row: 1
sum: 1.0000000000000002 for row: 2
sum: 1.0 for row: 3
sum: 0.9999999999999998 for row: 4
sum: 1.0 for row: 5
sum: 1.0 for row: 6
sum: 1.0 for row: 7
sum: 1.0 for row: 8
sum: 0.9999999999999999 for row: 9
sum: 1.0 for row: 10
sum: 1.0 for row: 11
sum: 1.0 for row: 12
sum: 1.0 for row: 13
sum: 1.0 for row: 14
sum: 1.0 for row: 15
sum: 1.0 for row: 16
sum: 1.0 for row: 17

In [273]:
df.to_csv("csv_files/detection_graph_softmax.csv", index=False)